Vagrant.configure(2) do |config|
    config.vm.box = "bento/ubuntu-16.04"

    config.vm.synced_folder "..", "/vagrant/pillow-perf"
    config.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 2
    end


    config.vm.provision "swap", type: "shell",
    inline: <<-SHELL
        # does the swap file already exist?
        grep -q "swapfile" /etc/fstab
        # if not then create it
        if [ $? -ne 0 ]; then
          echo 'swapfile not found. Adding swapfile.'
          fallocate -l 512M /swapfile
          chmod 600 /swapfile
          mkswap /swapfile
          swapon /swapfile
          echo '/swapfile none swap defaults 0 0' >> /etc/fstab
        else
          echo 'swapfile found. No changes made.'
        fi
    SHELL


    config.vm.provision "preinstall", type: "shell", path: "./install_ubuntu.sh"


    config.vm.provision "run", type: "shell", privileged: false, inline: <<-SHELL
        rsync -r /vagrant/pillow-perf ./ \
            --exclude=pillow-perf/docs/node_modules \
            --exclude=pillow-perf/.git
        CC="ccache cc" ./pillow-perf/auto/run.sh - --json
    SHELL
end
